name: tcc_sesi
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - network_tcc
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - vol_database:/var/lib/mysql

  app:
    image: python:3.11-slim
    container_name: app
    networks:
      - network_tcc
    working_dir: /app
    volumes:
      - ./src:/app
      - ./.docker/requirements.txt:/tmp/requirements.txt:ro
      - vol_images:/app/static/uploads
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DEBUG=${DEBUG}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    expose:
      - "5000"
    command: >
      sh -c "pip install --no-cache-dir -r /tmp/requirements.txt &&
             flask db upgrade &&
             python -m flask run --host=0.0.0.0 --port=5000"
    depends_on:
      - mysql

  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    networks:
      - network_tcc
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    networks:
      - network_tcc
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      PMA_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  vol_database:
    name: banco_de_dados_tcc
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.docker/mysql
  vol_images:
    name: imagens_tcc
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.docker/imagens

networks:
  network_tcc:
    driver: bridge
